package me.bookpay.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table CONSUME.
 */
public class Consume implements Serializable{

    private static final long serialVersionUID = 7534077750620010889L;
    private Long id;
    private String detail_Id;
    private String typeIcon;
    private String typeName;
    private String typeID;
    private String pic_Ids;
    private String money;
    private String starDate;
    private String endDate;
    private String city;
    private Integer count;
    private String description;

    public Consume() {
    }

    public Consume(Long id) {
        this.id = id;
    }

    public Consume(Long id, String detail_Id, String typeIcon, String typeName, String typeID, String pic_Ids, String money, String starDate, String endDate, String city, Integer count, String description) {
        this.id = id;
        this.detail_Id = detail_Id;
        this.typeIcon = typeIcon;
        this.typeName = typeName;
        this.typeID = typeID;
        this.pic_Ids = pic_Ids;
        this.money = money;
        this.starDate = starDate;
        this.endDate = endDate;
        this.city = city;
        this.count = count;
        this.description = description;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDetail_Id() {
        return detail_Id;
    }

    public void setDetail_Id(String detail_Id) {
        this.detail_Id = detail_Id;
    }

    public String getTypeIcon() {
        return typeIcon;
    }

    public void setTypeIcon(String typeIcon) {
        this.typeIcon = typeIcon;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public String getTypeID() {
        return typeID;
    }

    public void setTypeID(String typeID) {
        this.typeID = typeID;
    }

    public String getPic_Ids() {
        return pic_Ids;
    }

    public void setPic_Ids(String pic_Ids) {
        this.pic_Ids = pic_Ids;
    }

    public String getMoney() {
        return money;
    }

    public void setMoney(String money) {
        this.money = money;
    }

    public String getStarDate() {
        return starDate;
    }

    public void setStarDate(String starDate) {
        this.starDate = starDate;
    }

    public String getEndDate() {
        return endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
