package me.bookpay.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import me.bookpay.greendao.Consume;

import me.bookpay.greendao.ConsumeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig consumeDaoConfig;

    private final ConsumeDao consumeDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        consumeDaoConfig = daoConfigMap.get(ConsumeDao.class).clone();
        consumeDaoConfig.initIdentityScope(type);

        consumeDao = new ConsumeDao(consumeDaoConfig, this);

        registerDao(Consume.class, consumeDao);
    }
    
    public void clear() {
        consumeDaoConfig.getIdentityScope().clear();
    }

    public ConsumeDao getConsumeDao() {
        return consumeDao;
    }

}
